# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 966d27caf277551d852de60c40383e8422697c7473f5bfb051ceb5ee041ec64d03d0769ce59d9f009b1636f690ef7c6eeeadc226ec0645d6ad588105534e4f14

test:
  secret_key_base: ba37b662880694e780fd81b800267f245e9a6f6b5e9b39e29bf3b6e61b0a080109e5ba157202460ce2f0de0c2e42a18624185663750d41c2405a35fc2f5cfd69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
